# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Tags: /tags
  Categories: /categories
  Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: YYYY-MM

# Comments.
comments:
  # Disqus comments
  disqus_shortname:
  #disqus_shortname: orpyhw

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
#instagram_url: https://www.instagram.com/
#dribble_url: https://dribbble.com/
github_url: https://github.com/whypro
#googleplus_url: https://plus.google.com/
#behance_url: https://www.behance.net/
#fivehundredpx_url: https://500px.com/
email_url: whypro@live.cn
rss_url: \#

# Footer About Text
footer_about: "This theme was developed by <a href=\"https://github.com/klugjo\">Jonathan Klughertz</a>. The source code is available on Github. Create Websites. Make Magic."

# Footer Copyright Line
footer_copyright: "@Everlasting. All right reserved | Design & Hexo <a href=\"http://whypro.github.io/hexo-blog/\">whypro</a>"

