slogan: "Don't think twice, it's all right."

show_heart: true

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    # icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    # icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    # icon: "fa fa-tags"
  - title: About
    url: about.html
    intro: "About me."
    # icon: "fa fa-user"
  - title: RSS
    url: atom.xml
    intro: "Subscribe me."
    # icon: "fa fa-user"

links:
  - title: Freemind.386
    url: https://github.com/blackshow/hexo-theme-freemind.386
    intro: "Freemind.386's Github repository."
    icon: "fa fa-github"
  - title: "My Github"
    url: https://www.github.com/whypro
    intro: "My Github account."
    icon: "fa fa-github"
  # - title: "My LinkedIn"
  #   url: http://www.linkedin.com/in/xxx
  #   intro: "My Linkin account."
  #   icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname:


# Analytics (change to yours)
google_analytics:
  enable: false
  siteid: 
baidu_tongji:
  enable: true
  siteid: 17e1c6a0010d7be7e49ae6d2c2e7b817

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
